### ISSUE TITLE
For loop is not correct

### ISSUE THREAD

**Issue by mhamidjamil** [ahmadsh3ikh/Day_2_code#1]
in your for loop, you have re-initialized the hours variable, optimize it.

**Comment by ahmadsh3ikh** [comment]
Issue Resolved @mhamidjamil Please Check

**Comment by mhamidjamil** [comment]
seems fine now you can close the issue. @ahmadsh3ikh

**Comment by ahmadsh3ikh** [comment]
ok @mhamidjamil
