### ISSUE TITLE
assignment 3, sum up the user input number and show it on terminal

### ISSUE THREAD

**Issue by mhamidjamil** [ahmadsh3ikh/Day_2_code#2]
Create new file in the same directory and set file name as code3.cpp and in this code, terminal should take input from user make sure the input is between 0 and 9999 and then return the sum of its digits; i.e if user enter _245_, code should return (_only_) its sum (2+4+5 = ) **11**
Hint:
int newVar = 234 / 10;   //  newVar will be 23
int newValue = 234 % 10;   // newValue will be 4
Understand how **break;** keyword work.
@ahmadsh3ikh you have to finish it till tomorrow night.

**Comment by mhamidjamil** [comment]
Reminder!
@ahmadsh3ikh today you have to close this issue after uploading verified code.

**Comment by ahmadsh3ikh** [comment]
Done @mhamidjamil
