### ISSUE TITLE
final assignment

### ISSUE THREAD

**Issue by mhamidjamil** [ahmadsh3ikh/Day_2_code#5]
Create a new file in the same directory and name it `a4f.cpp`, 

> What you have to do? 
Step 1:

Write me a code in which terminal takes two numbers from user, say user input 2 and 30 divide the higher number from lower number `30/2` and save the _result_ in a variable, in our case it is `30/2 = `15, then divide it again and again until the _result_ becomes less than 10. _**Hint:** Result will be 7 in this case._

> Step 2: 

then print the difference of the result from higher number user enter to the lower number.
`(do step one show the result then the step 2 will be explained in detail) `

**Comment by ahmadsh3ikh** [comment]
Ustad pehle step 1 taa smjhaa 10 wje aa k.. uttu phir giya ey

**Comment by mhamidjamil** [comment]
@ahmadsh3ikh kindly read it again, I have updated it a bit for better understanding.
**Remember** you have to understand it yourself.
_you are not just learning how to code, you are also learning how to understand the problem._

**Comment by mhamidjamil** [comment]
here is the step 2:
say user enter 30 and 2 and when we divide greater number from the smaller one, again and again until the value become less then 10, 7 in our case, then multiply it with the higher number user enter but after adding the smaller number in it, `(7+2)*30 = 270` then use any loop to print the number from the 270 to 0, which are dividable from `7+2 =` 9.
@ahmadsh3ikh

**Comment by ahmadsh3ikh** [comment]
Done @mhamidjamil
