### ISSUE TITLE
Test Code

### ISSUE THREAD

**Issue by mhamidjamil** [ahmadsh3ikh/Day_2_code#6]
Create new file name if testCode.cpp

> **Step 1 :**

You have to write a code which take input from user like this:
`Enter First number: `(say user input 34)
After taking first input the code should take the second input number which should be greater than the first number,
`Enter Second Number: `(say user input 20)
`(Second number should be greater than 34) Enter second Number again: `
prompt this until user input second number which is greater than the first number.

> output should be as same as pointed in highlighted parts.

> **Step 2:**

Now you have smaller number in `input1` and large number in `input2` variable.
now multiply small number and greater number and store there result in `result` variable and use any loop to print the number which are dividable from 3 and 5, from `result` value to 0.

**Comment by ahmadsh3ikh** [comment]
@mhamidjamil done.
