### ISSUE TITLE
last assignment before functions

### ISSUE THREAD

**Issue by mhamidjamil** [ahmadsh3ikh/Day_2_code#7]
Create a file and name it class.cpp:
Write me a code in which the user enter two numbers which will be sorted into small and large variable as you learned in previous videos, and after arranging small and large number use while loop to print all those numbers from greater number to smaller number which are dividable from 2 and 3 but not with 5.
@ahmadsh3ikh and also try to what is an array and also search how functions work in cpp language.

**Comment by mhamidjamil** [comment]
You haven't closed the assignment yet, so now write me a code using `while loop` instead of `for `loop, and remember always ask me before closing the assignment and also mention this point to mahmood, don't close any assignment until I approve your task.
@ahmadsh3ikh

**Comment by ahmadsh3ikh** [comment]
done @mhamidjamil

**Comment by mhamidjamil** [comment]
Don't you read my last comment carefully? @ahmadsh3ikh

**Comment by mhamidjamil** [comment]
Accepted, I'm closing this Assignment now.
